name: Gosoline

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:

  test:
    name: Build + Test
    runs-on: ubuntu-18.04
    steps:

      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Execute terraform fmt -check -recursive .
        run: terraform fmt -check -recursive .

      - name: Execute gofmt -l .
        run: gofmt -l .

      - name: Execute test -z $(gofmt -l .)
        run: test -z $(gofmt -l .)

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: Build
        run: go build -v ./...

      - name: Static code analysis
        run: go vet ./...

      - name: Test
        run: go test ./...

      - name: Integration tests
        run: go test -p 1 --tags='integration,fixtures' ./test/...
